spring:
  application:
    name: kafkatest
  mvc:
    servlet:
      load-on-startup: 1
  kafka:
    producer:
    #110.211.99.254本机IP为了容器能访问
      bootstrap-servers: 10.211.99.254:9092
    consumer:
      #指定消息被消费之后自动提交偏移量（即消息的编号，表示消费到了哪个位置，消费者每消费完一条消息就会向kafka服务器汇报自己消消费到的那个消息的下次继续消费编号，以便于
      enable-auto-commit: true
      #消费者组
      group-id: kafka-group
      #从最近的地方开始消费
      auto-offset-reset: latest
      #可设置多个
      bootstrap-servers: 10.211.99.254:9092
      max-poll-records: 10
server:
  port: ${PORT:7002}